---
- hosts: webservers
  become: yes
  tasks: 
  - include_tasks: myfiles.yml
  - name: i want to instal webserver on ubuntu
    apt:
     name: apache2
     state: present 

  - name: i want to start webserver
    service:
      name: apache2
      state: started

  - name: i want to copy index file  into all nodes
    template:
      src:
      dest: /var/www/html/index.html

  - name: i have to restart webserver
    service:
      name: apache2
      state: restarted

  
      
    