---
- hosts: webservers
  become: yes
  tasks: 
  - include_tasks: myfiles.yml
  - name: i want to instal webserver on ubuntu
    apt:
     name: apache2
     state: present 
    notify: startwebserver

  - name: i want to copy index file  into all nodes
    template:
      src: index.j2
      dest: /var/www/html/index.html
    notify: restartwebserver

  handlers:
  - name: startwebserver
    service:
      name: apache2
      state: started

  - name: restartwebserver
    service:
      name: apache2
      state: restarted


  
      
    