---
# tasks file for mytomrole
- name: install tomcat
  yum:
   name: tomcat
   state: present

- name: copy tomcat config file into all nodes
  template:
    src:  templates/tomconfig.j2
    dest:  /usr/share/tomcat/conf/tomcat.conf
  notify: starttomcat
  
- name: Install Admin Packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
   - tomcat-webapps
   - tomcat-admin-webapps

- name: copy tom user file into all nodes 
  template:
    src: templates/tomuser.j2
    dest: /usr/share/tomcat/conf/tomcat-users.xml
  notify: restarttomcat

- name: deploy maha java war file into all nodes 
  get_url:
    url: https://s3.amazonaws.com/maha4iac/mahaLogin.war
    dest: /usr/share/tomcat/webapps/mahaLogin.war
    force_basic_auth: yes
  notify: restarttomcat
